FROM python:3.8

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8055

CMD gunicorn django_site.wsgi:application -t 200 --bind 0.0.0.0:8055 --log-level debug